name: '🛫 Build and Upload to Itch'


# Whenever a tag push matching pattern "v*" then run the job
on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  ITCH_GAME: yesnoslap
  ITCH_USER: mitchkmiller


jobs:
  prepareGodot:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Don't cancel other OS runners if one fails.
      fail-fast: false
      matrix:
        # Put the operating systems you want to run on here.
        os: [ubuntu-latest]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - uses: actions/checkout@v3
        name: 🧾 Checkout
        with:
          lfs: true

      - name: export game
        id: export
        # Use latest version (see releases for all versions)
        uses: firebelley/godot-export@v5.2.0
        with:
          # Defining all the required inputs
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2.1/Godot_v4.2.1-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: true

      - name: CD
        run: ls -R

      - name: Upload windows build to itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: windows-x64
          PACKAGE: ./Exports/yesnoslap-windows.zip

      - name: Upload linux build to itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: linux
          PACKAGE: ./Exports/yesnoslap-linux.zip

      - name: Upload mac build to itch
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          CHANNEL: osx
          PACKAGE: ./Exports/yesnoslap-mac.zip
